name: Tests dev

on:
  schedule:
    # check once a week on mondays
    - cron: '0 10 * * 1'

jobs:
  tests-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tests dependencies
      run: python -m pip install tox

    - name: run Python tests
      run: |
        tox -e upet-tests-dev
      env:
        # Use the CPU only version of torch when building/running the code
        PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
